apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      nodeSelector:
        topology.kubernetes.io/region: hm2
      containers:
        - name: mqtt
          image: eclipse-mosquitto
          ports:
            - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
  selector:
    app: mqtt